/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/cargo.glb --transform --types --output src/components/models/Cargo.tsx 
Files: public/models/cargo.glb [21.79MB] > /home/gift/Documents/ship-radar/src/components/models/cargo-transformed.glb [2.42MB] (89%)
Author: gogiart (https://sketchfab.com/agt14032013)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cargo-ship-02-22135f8937194b6aba964b05e3608620
Title: Cargo Ship 02
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_16: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_19: THREE.Mesh
    Object_20: THREE.Mesh
    Object_21: THREE.Mesh
    Object_22: THREE.Mesh
    Object_23: THREE.Mesh
    Object_24: THREE.Mesh
    Object_25: THREE.Mesh
    Object_37: THREE.Mesh
    Object_38: THREE.Mesh
    Object_40: THREE.Mesh
    Object_4: THREE.Mesh
  }
  materials: {
    acmat_1: THREE.LineBasicMaterial
    acmat_10: THREE.MeshStandardMaterial
    acmat_13: THREE.MeshStandardMaterial
    acmat_15: THREE.MeshStandardMaterial
    acmat_14: THREE.MeshStandardMaterial
    acmat_17: THREE.MeshStandardMaterial
    acmat_18: THREE.MeshStandardMaterial
    acmat_19: THREE.MeshStandardMaterial
    acmat_20: THREE.MeshStandardMaterial
    acmat_21: THREE.MeshStandardMaterial
    acmat_22: THREE.MeshStandardMaterial
    acmat_23: THREE.MeshStandardMaterial
    acmat_24: THREE.MeshStandardMaterial
    acmat_25: THREE.MeshStandardMaterial
    acmat_26: THREE.MeshStandardMaterial
    acmat_27: THREE.MeshStandardMaterial
    acmat_28: THREE.MeshStandardMaterial
    acmat_3: THREE.MeshStandardMaterial
    acmat_5: THREE.MeshStandardMaterial
    acmat_6: THREE.MeshStandardMaterial
    acmat_1: THREE.MeshStandardMaterial
    acmat_9: THREE.MeshStandardMaterial
    acmat_0: THREE.MeshStandardMaterial
    acmat_16: THREE.MeshStandardMaterial
    acmat_2: THREE.MeshStandardMaterial
    acmat_7: THREE.MeshStandardMaterial
    acmat_12: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/cargo-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <lineSegments geometry={nodes.Object_32.geometry} material={materials.acmat_1} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_2.geometry} material={materials.acmat_10} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.acmat_13} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.acmat_15} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.acmat_14} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.acmat_17} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.acmat_18} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.acmat_19} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.acmat_20} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.acmat_21} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.acmat_22} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.acmat_23} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.acmat_24} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.acmat_25} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.acmat_26} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.acmat_27} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.acmat_28} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.acmat_3} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.acmat_5} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.acmat_6} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.acmat_1} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.acmat_9} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_25.geometry} material={materials.acmat_0} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_37.geometry} material={materials.acmat_16} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.acmat_2} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.acmat_7} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.acmat_12} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/cargo-transformed.glb')
