/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/fishing.glb --transform --types --output src/components/models/Fishing.tsx 
Files: public/models/fishing.glb [52.22MB] > /home/gift/Documents/ship-radar/src/components/models/fishing-transformed.glb [5MB] (90%)
Author: Vasanth adepu (https://sketchfab.com/vasanthadepu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fishing-boat-1e0371ad73e14e29a13464a54105e80a
Title: fishing boat
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import type { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js'

type ActionName = 'Take 001'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    polySurface202_aiStandardSurface1_0: THREE.Mesh
    polySurface202_aiStandardSurface2_0: THREE.Mesh
    polySurface202_aiStandardSurface3_0: THREE.Mesh
    polySurface202_aiStandardSurface4_0: THREE.Mesh
  }
  materials: {
    aiStandardSurface1: THREE.MeshStandardMaterial
    aiStandardSurface2: THREE.MeshStandardMaterial
    aiStandardSurface3: THREE.MeshStandardMaterial
    aiStandardSurface4: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/models/fishing-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.082}>
          <group name="polySurface202" position={[1.296, 8.667, 2.269]} rotation={[0, 0.653, 0]}>
            <mesh name="polySurface202_aiStandardSurface1_0" geometry={nodes.polySurface202_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} />
            <mesh name="polySurface202_aiStandardSurface2_0" geometry={nodes.polySurface202_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
            <mesh name="polySurface202_aiStandardSurface3_0" geometry={nodes.polySurface202_aiStandardSurface3_0.geometry} material={materials.aiStandardSurface3} />
            <mesh name="polySurface202_aiStandardSurface4_0" geometry={nodes.polySurface202_aiStandardSurface4_0.geometry} material={materials.aiStandardSurface4} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/fishing-transformed.glb')
