/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/generic.glb --transform --types --output src/components/models/Generic.tsx 
Files: public/models/generic.glb [17.32MB] > /home/gift/Documents/ship-radar/src/components/models/generic-transformed.glb [581.63KB] (97%)
Author: baby_silk (https://sketchfab.com/baby_silk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/black-and-blue-cruise-ship-3acbbe6269234a22b93f7e44aa8b1798
Title: Black And Blue Cruise Ship
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js'

type GLTFResult = GLTF & {
  nodes: {
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
  }
  materials: {
    material: THREE.MeshStandardMaterial
    material_1: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/generic-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_6.geometry} material={materials.material} position={[0, -0.18, 0.743]} rotation={[0, Math.PI / 2, 0]} scale={0.025} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.material_1} position={[0, -0.18, 0.743]} rotation={[0, Math.PI / 2, 0]} scale={0.025} />
    </group>
  )
}

useGLTF.preload('/models/generic-transformed.glb')
