/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/military.glb --transform --types --output src/components/models/Military.tsx 
Files: public/models/military.glb [5.21MB] > /home/gift/Documents/ship-radar/src/components/models/military-transformed.glb [400.76KB] (92%)
Author: SIpriv (https://sketchfab.com/S1Priv)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-uss-nimitz-acc8e2ab9cff4f6aa41c7f6db5e59abb
Title: Low-poly Uss nimitz
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import type { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js'

type ActionName = 'animation radar jimitz'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_32: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_35: THREE.Mesh
    Object_53: THREE.Mesh
    Object_54: THREE.Mesh
    Object_55: THREE.Mesh
    Object_56: THREE.Mesh
    Object_57: THREE.Mesh
    Object_58: THREE.Mesh
    Object_59: THREE.Mesh
    Object_60: THREE.Mesh
    Object_61: THREE.Mesh
    Object_62: THREE.Mesh
    Object_63: THREE.Mesh
    Object_86: THREE.Mesh
    Object_88: THREE.Mesh
  }
  materials: {
    material_2: THREE.MeshStandardMaterial
    material_0: THREE.MeshStandardMaterial
    material_1: THREE.MeshStandardMaterial
    material_3: THREE.MeshStandardMaterial
    material_4: THREE.MeshStandardMaterial
    material_5: THREE.MeshStandardMaterial
    material_6: THREE.MeshStandardMaterial
    material_7: THREE.MeshStandardMaterial
    material_8: THREE.MeshStandardMaterial
    material_9: THREE.MeshStandardMaterial
    material_10: THREE.MeshStandardMaterial
    material_11: THREE.MeshStandardMaterial
    material_12: THREE.MeshStandardMaterial
    material_13: THREE.MeshStandardMaterial
    material_14: THREE.MeshStandardMaterial
    material_15: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/models/military-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="group9_42" position={[1.313, 0.7, 5.313]}>
          <group name="group10_41" position={[0, 0.525, 0]}>
            <group name="mesh_40" position={[0, -0.006, -0.001]}>
              <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.material_2} />
            </group>
          </group>
        </group>
        <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.material_0} position={[0.85, 0.656, -0.708]} rotation={[0, 0, 0.14]} />
        <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.material_1} position={[0.85, 0.656, -0.708]} rotation={[0, 0, 0.14]} />
        <mesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.material_3} position={[-1.469, 0.811, 3.237]} rotation={[0, -1.265, 0]} />
        <mesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials.material_4} position={[0, 0.387, 0]} />
        <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.material_5} position={[0, 0.387, 0]} />
        <mesh name="Object_55" geometry={nodes.Object_55.geometry} material={materials.material_6} position={[0, 0.387, 0]} />
        <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.material_7} position={[0, 0.387, 0]} />
        <mesh name="Object_57" geometry={nodes.Object_57.geometry} material={materials.material_8} position={[0, 0.387, 0]} />
        <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.material_9} position={[0, 0.387, 0]} />
        <mesh name="Object_59" geometry={nodes.Object_59.geometry} material={materials.material_10} position={[0, 0.387, 0]} />
        <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.material_11} position={[0, 0.387, 0]} />
        <mesh name="Object_61" geometry={nodes.Object_61.geometry} material={materials.material_12} position={[0, 0.387, 0]} />
        <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.material_13} position={[0, 0.387, 0]} />
        <mesh name="Object_63" geometry={nodes.Object_63.geometry} material={materials.material_2} position={[0, 0.387, 0]} />
        <mesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials.material_14} position={[-0.063, 0.717, -3.987]} rotation={[3.137, 0, Math.PI]} />
        <mesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.material_15} position={[1.506, 0.863, 4.119]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/military-transformed.glb')
