/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/passenger.glb --transform --types --output src/components/models/Passenger.tsx 
Files: public/models/passenger.glb [2.1MB] > /home/gift/Documents/ship-radar/src/components/models/passenger-transformed.glb [196.46KB] (91%)
Author: FHA_studios (https://sketchfab.com/FHA_ships)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/viking-line-ms-viking-grace-2013-b111f1e11fd842cfbe7d4504964242b4
Title: Viking Line M/S Viking Grace (2013)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_34: THREE.Mesh
    Object_62: THREE.Mesh
  }
  materials: {
    ['Black112.001']: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
    ['kaide-removebg-preview.001']: THREE.MeshStandardMaterial
    ['kaidevalk-removebg-preview.001']: THREE.MeshStandardMaterial
    ['Material.034']: THREE.MeshStandardMaterial
    ['VikingLogo-removebg-preview.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/passenger-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Black112.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials['kaide-removebg-preview.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials['kaidevalk-removebg-preview.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials['Material.034']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_62.geometry} material={materials['VikingLogo-removebg-preview.001']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/passenger-transformed.glb')
