/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/tanker.glb --transform --types --output src/components/models/Tanker.tsx 
Files: public/models/tanker.glb [10.2MB] > /home/gift/Documents/ship-radar/src/components/models/tanker-transformed.glb [424.53KB] (96%)
Author: KoreanNavy (https://sketchfab.com/KoreanNavy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tanker-ship-96ebf61af42b4062ae98a6ad848e1a25
Title: Tanker Ship
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import type { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js'

type ActionName = 'Animation'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_77: THREE.Mesh
    Object_79: THREE.Mesh
    Object_4: THREE.Mesh
    Object_11: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/models/tanker-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group name="Cube014_30" position={[-0.814, 20.385, 84.268]} rotation={[-Math.PI, 0, 0]} scale={[0.506, 0.02, 0.069]}>
            <mesh name="Object_77" geometry={nodes.Object_77.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube015_31" position={[0.809, 20.395, 84.61]} rotation={[-Math.PI, -0.157, 0]} scale={[0.506, 0.02, 0.069]}>
            <mesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials.PaletteMaterial001} />
          </group>
        </group>
        <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} scale={[9.425, 5.042, 50.931]} />
        <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.PaletteMaterial002} scale={[9.425, 5.042, 50.931]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/tanker-transformed.glb')
