/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/yacht.glb --transform --types --output src/components/models/Yacht.tsx 
Files: public/models/yacht.glb [5.59MB] > /home/gift/Documents/ship-radar/src/components/models/yacht-transformed.glb [386.02KB] (93%)
Author: assetfactory (https://sketchfab.com/assetfactory)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/animated-yacht-9c8d4abcf4224fc1811e5a88530deaf8
Title: Animated Yacht
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import type { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js'

type ActionName = 'Armature|ArmatureAction'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_39: THREE.SkinnedMesh
    Object_40: THREE.SkinnedMesh
    Object_42: THREE.SkinnedMesh
    Object_44: THREE.SkinnedMesh
    Object_45: THREE.SkinnedMesh
    Object_47: THREE.SkinnedMesh
    Object_48: THREE.SkinnedMesh
    Object_50: THREE.SkinnedMesh
    Object_51: THREE.SkinnedMesh
    Object_53: THREE.SkinnedMesh
    Object_54: THREE.SkinnedMesh
    Object_56: THREE.SkinnedMesh
    Object_57: THREE.SkinnedMesh
    Object_58: THREE.SkinnedMesh
    Object_59: THREE.SkinnedMesh
    Object_61: THREE.SkinnedMesh
    Object_63: THREE.SkinnedMesh
    Object_64: THREE.SkinnedMesh
    Object_66: THREE.SkinnedMesh
    Object_68: THREE.SkinnedMesh
    Object_70: THREE.SkinnedMesh
    Object_71: THREE.SkinnedMesh
    Object_73: THREE.SkinnedMesh
    Object_75: THREE.SkinnedMesh
    Object_77: THREE.SkinnedMesh
    Object_79: THREE.SkinnedMesh
    Object_81: THREE.SkinnedMesh
    Object_83: THREE.SkinnedMesh
    Object_85: THREE.SkinnedMesh
    Object_87: THREE.SkinnedMesh
    Object_88: THREE.SkinnedMesh
    Object_90: THREE.SkinnedMesh
    Object_92: THREE.SkinnedMesh
    Object_93: THREE.SkinnedMesh
    Object_95: THREE.SkinnedMesh
    Object_97: THREE.SkinnedMesh
    Object_98: THREE.SkinnedMesh
    Object_100: THREE.SkinnedMesh
    Object_101: THREE.SkinnedMesh
    Object_103: THREE.SkinnedMesh
    Object_104: THREE.SkinnedMesh
    Object_106: THREE.SkinnedMesh
    Object_108: THREE.SkinnedMesh
    Object_109: THREE.SkinnedMesh
    Object_111: THREE.SkinnedMesh
    Object_113: THREE.SkinnedMesh
    Object_115: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    PaletteMaterial001: THREE.MeshPhysicalMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    Wood: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useGLTF('/models/yacht-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_39.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_40.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_42.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_44.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_45" geometry={nodes.Object_45.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_45.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_47.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_48.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_50.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_51" geometry={nodes.Object_51.geometry} material={materials.Wood} skeleton={nodes.Object_51.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_53.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.Wood} skeleton={nodes.Object_54.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_56.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_57" geometry={nodes.Object_57.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_57.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.Wood} skeleton={nodes.Object_58.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_59" geometry={nodes.Object_59.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_59.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_61" geometry={nodes.Object_61.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_61.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_63" geometry={nodes.Object_63.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_63.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.Wood} skeleton={nodes.Object_64.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_66.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_68.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.Wood} skeleton={nodes.Object_70.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_71" geometry={nodes.Object_71.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_71.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_73" geometry={nodes.Object_73.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_73.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_75" geometry={nodes.Object_75.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_75.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_77" geometry={nodes.Object_77.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_77.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials.Wood} skeleton={nodes.Object_79.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_81" geometry={nodes.Object_81.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_81.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_83.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_85" geometry={nodes.Object_85.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_85.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_87" geometry={nodes.Object_87.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_87.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_88.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_90.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_92.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_93" geometry={nodes.Object_93.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_93.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_95" geometry={nodes.Object_95.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_95.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_97" geometry={nodes.Object_97.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_97.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_98.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_100.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_101" geometry={nodes.Object_101.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_101.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_103" geometry={nodes.Object_103.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_103.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_104.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_106.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_108.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_109" geometry={nodes.Object_109.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_109.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_111" geometry={nodes.Object_111.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_111.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_113" geometry={nodes.Object_113.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_113.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
        <skinnedMesh name="Object_115" geometry={nodes.Object_115.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_115.skeleton} rotation={[-Math.PI / 2, -1.571, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/yacht-transformed.glb')
